src/Entity/Laptop.php
<?php

namespace App\Entity;

use App\Repository\LaptopRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=LaptopRepository::class)
 */
class Laptop
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $ramMemory;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $ramTechology;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $ramFrequency;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $hardDisk;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $hardDiskTechnology;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $processorMaker;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $processorModel;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $processorVelocity;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $processorCore;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $processorCache;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $graphicMaker;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $graphicModel;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $graphicTechnology;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $graphicCapacity;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $graphicInterface;

    /**
     * @ORM\Column(type="integer")
     */
    private $usb2_0;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $usb3_0;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $hdmi;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $dvi;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $bluetooht;

    /**
     * @ORM\Column(type="string", length=5, nullable=true)
     */
    private $bluetooht_version;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $screenSize;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $screenResolution;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $screenFrequency;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $batteryCapacity;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $batteryChargeTime;

    /**
     * @ORM\ManyToOne(targetEntity=SubCategory::class, inversedBy="laptops")
     * @ORM\JoinColumn(nullable=false)
     */
    private $idSubcategory;

    /**
     * @ORM\ManyToOne(targetEntity=Product::class, inversedBy="laptops")
     * @ORM\JoinColumn(nullable=false)
     */
    private $idProduct;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $os;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRamMemory(): ?string
    {
        return $this->ramMemory;
    }

    public function setRamMemory(string $ramMemory): self
    {
        $this->ramMemory = $ramMemory;

        return $this;
    }

    public function getRamTechology(): ?string
    {
        return $this->ramTechology;
    }

    public function setRamTechology(string $ramTechology): self
    {
        $this->ramTechology = $ramTechology;

        return $this;
    }

    public function getRamFrequency(): ?string
    {
        return $this->ramFrequency;
    }

    public function setRamFrequency(?string $ramFrequency): self
    {
        $this->ramFrequency = $ramFrequency;

        return $this;
    }

    public function getHardDisk(): ?string
    {
        return $this->hardDisk;
    }

    public function setHardDisk(string $hardDisk): self
    {
        $this->hardDisk = $hardDisk;

        return $this;
    }

    public function getHardDiskTechnology(): ?string
    {
        return $this->hardDiskTechnology;
    }

    public function setHardDiskTechnology(string $hardDiskTechnology): self
    {
        $this->hardDiskTechnology = $hardDiskTechnology;

        return $this;
    }

    public function getProcessorMaker(): ?string
    {
        return $this->processorMaker;
    }

    public function setProcessorMaker(string $processorMaker): self
    {
        $this->processorMaker = $processorMaker;

        return $this;
    }

    public function getProcessorModel(): ?string
    {
        return $this->processorModel;
    }

    public function setProcessorModel(string $processorModel): self
    {
        $this->processorModel = $processorModel;

        return $this;
    }

    public function getProcessorVelocity(): ?string
    {
        return $this->processorVelocity;
    }

    public function setProcessorVelocity(string $processorVelocity): self
    {
        $this->processorVelocity = $processorVelocity;

        return $this;
    }

    public function getProcessorCore(): ?string
    {
        return $this->processorCore;
    }

    public function setProcessorCore(string $processorCore): self
    {
        $this->processorCore = $processorCore;

        return $this;
    }

    public function getProcessorCache(): ?string
    {
        return $this->processorCache;
    }

    public function setProcessorCache(string $processorCache): self
    {
        $this->processorCache = $processorCache;

        return $this;
    }

    public function getGraphicMaker(): ?string
    {
        return $this->graphicMaker;
    }

    public function setGraphicMaker(string $graphicMaker): self
    {
        $this->graphicMaker = $graphicMaker;

        return $this;
    }

    public function getGraphicModel(): ?string
    {
        return $this->graphicModel;
    }

    public function setGraphicModel(string $graphicModel): self
    {
        $this->graphicModel = $graphicModel;

        return $this;
    }

    public function getGraphicTechnology(): ?string
    {
        return $this->graphicTechnology;
    }

    public function setGraphicTechnology(string $graphicTechnology): self
    {
        $this->graphicTechnology = $graphicTechnology;

        return $this;
    }

    public function getGraphicCapacity(): ?string
    {
        return $this->graphicCapacity;
    }

    public function setGraphicCapacity(string $graphicCapacity): self
    {
        $this->graphicCapacity = $graphicCapacity;

        return $this;
    }

    public function getGraphicInterface(): ?string
    {
        return $this->graphicInterface;
    }

    public function setGraphicInterface(string $graphicInterface): self
    {
        $this->graphicInterface = $graphicInterface;

        return $this;
    }

    public function getUsb20(): ?int
    {
        return $this->usb2_0;
    }

    public function setUsb20(int $usb2_0): self
    {
        $this->usb2_0 = $usb2_0;

        return $this;
    }

    public function getUsb30(): ?int
    {
        return $this->usb3_0;
    }

    public function setUsb30(?int $usb3_0): self
    {
        $this->usb3_0 = $usb3_0;

        return $this;
    }

    public function getHdmi(): ?int
    {
        return $this->hdmi;
    }

    public function setHdmi(?int $hdmi): self
    {
        $this->hdmi = $hdmi;

        return $this;
    }

    public function getDvi(): ?int
    {
        return $this->dvi;
    }

    public function setDvi(?int $dvi): self
    {
        $this->dvi = $dvi;

        return $this;
    }

    public function getBluetooht(): ?int
    {
        return $this->bluetooht;
    }

    public function setBluetooht(?int $bluetooht): self
    {
        $this->bluetooht = $bluetooht;

        return $this;
    }

    public function getBluetoohtVersion(): ?string
    {
        return $this->bluetooht_version;
    }

    public function setBluetoohtVersion(?string $bluetooht_version): self
    {
        $this->bluetooht_version = $bluetooht_version;

        return $this;
    }

    public function getScreenSize(): ?string
    {
        return $this->screenSize;
    }

    public function setScreenSize(?string $screenSize): self
    {
        $this->screenSize = $screenSize;

        return $this;
    }

    public function getScreenResolution(): ?string
    {
        return $this->screenResolution;
    }

    public function setScreenResolution(string $screenResolution): self
    {
        $this->screenResolution = $screenResolution;

        return $this;
    }

    public function getScreenFrequency(): ?string
    {
        return $this->screenFrequency;
    }

    public function setScreenFrequency(?string $screenFrequency): self
    {
        $this->screenFrequency = $screenFrequency;

        return $this;
    }

    public function getBatteryCapacity(): ?string
    {
        return $this->batteryCapacity;
    }

    public function setBatteryCapacity(?string $batteryCapacity): self
    {
        $this->batteryCapacity = $batteryCapacity;

        return $this;
    }

    public function getBatteryChargeTime(): ?string
    {
        return $this->batteryChargeTime;
    }

    public function setBatteryChargeTime(?string $batteryChargeTime): self
    {
        $this->batteryChargeTime = $batteryChargeTime;

        return $this;
    }

    public function getIdSubcategory(): ?SubCategory
    {
        return $this->idSubcategory;
    }

    public function setIdSubcategory(?SubCategory $idSubcategory): self
    {
        $this->idSubcategory = $idSubcategory;

        return $this;
    }

    public function getIdProduct(): ?Product
    {
        return $this->idProduct;
    }

    public function setIdProduct(?Product $idProduct): self
    {
        $this->idProduct = $idProduct;

        return $this;
    }

    public function getOs(): ?string
    {

src/Controller/LaptopController.php
<?php

namespace App\Controller;

use App\Repository\SubCategoryRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class LaptopController extends AbstractController
{
    /**
     * @Route("/listSubCategories/Portatiles", name="app_listSubCategoriesPortatiles")
     */
    public function listSubCategoriesPortatil (SubCategoryRepository $SubCategoryRepository): Response{
        $SubCategory = $SubCategoryRepository->findOneBy(['name' => 'Portatil']);
        $productsLaptops = [];
        $laptops = null;
       
        $laptops = $SubCategory->getLaptops();
        foreach ($laptops as $d) {
            array_push($productsLaptops, $d->getIdProduct());
        }

        return $this->render('subcategory/portatil.html.twig', [
            'productsLaptops' => $productsLaptops,
            'laptops' => $laptops
        ]);
    }

}

templates/laptop/laptop.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello laptopController!
{% endblock %}

{% block body %}
	<div class="col-12 row justify-content-xs-center justify-content-lg-around mt-5">
		<div class="col-xs-11 col-lg-4 offset-xs-1 offset-lg-1 row justify-content-center">
			<img class="" src="{{ asset('images/Laptops/' ~ product.picture ) }}" alt="Card image cap" width"500px" height="500px"/>
		</div>

		<div class="col-xs-11 col-lg-6 row justify-content-xs-center justify-content-lg-start">
			<h1 class="h2 col-xs-3 offset-xs-1 col-lg-11 mt-4 text-center text-lg-left">
				{{product.name}}
			</h1>
			<h4 class="h4 col-xs-3 col-lg-11 mt-4 lead">
				Fabricante:
				{{product.mark}}
			</h4>
			<h4 class="h4 col-xs-3 col-lg-11 mt-4 lead">
				Modelo:
				{{product.model}}
			</h4>
			<h4 class=" h4 col-xs-3 col-lg-11 mt-4 lead">
				Memoria RAM:
				{{laptop.ramMemory}}
				{{laptop.ramTechology}}</h4>
			<h4 class=" h4 col-xs-3 col-lg-11 mt-4 lead">
				Procesador:
				{{laptop.processorMaker}}
				{{laptop.processorModel}}</h4>
			<h4 class=" h4 col-xs-3 col-lg-11 mt-4 lead">
				Tarjeta gráfica:
				{{laptop.graphicMaker}}
				{{laptop.graphicModel}}
				{{laptop.graphicCapacity}}</h4>
			<h4 class=" h4 col-xs-3 col-lg-11 mt-4 lead">
				S.O.:
				{{laptop.os}}</h4>
			<h4 class=" h4 col-xs-3 col-lg-11 mt-4 lead">
				Precio:
				{{product.price}}
				$</h4>
			<select id="stockSelect"class="col-xs-12  col-lg-6 mt-4 lead form-select" aria-label="Default select example">
				<option selected>1</option>
                {% for i in 2..product.stock %}
                    <option value="1">{{ i }}</option>
                {% endfor %}
			</select>
			<div class="w-100"></div>
			<button href="" onClick="checkAddCart({{product.id}})"  class=" col-xs-12 col-lg-6 mt-4 lead btn btn-primary">
				Añadir al carrito
			</button>
		</div>
		<div class="col-xs-11 col-lg-6 mt-3 row">
			<h2 class="h2 col-12">
				Descripción</h2>
			<p class="p col-12 leaf text-align-justify">
				{{product.description}}
			</p>
			<table class="mt-4 col-12 table">
				<tbody>
					<tr>
						<th scope="row">Fabricante</th>
						<td>{{product.maker}}</td>
					</tr>
					<tr>
						<th scope="row">Nombre</th>
						<td>{{product.name}}</td>
					</tr>
					<tr>
						<th scope="row">Modelo</th>
						<td>{{product.model}}</td>
					</tr>
					<tr>
						<th scope="row">Dimensiones</th>
						<td>{{product.dimensions}}</td>
					</tr>
					<tr>
						<th scope="row">Peso</th>
						<td>{{product.weight}}</td>
					</tr>
					<tr>
						<th scope="row">Año</th>
						<td>{{product.year}}</td>
					</tr>
					<tr>
						<th scope="row">Capacidad de la memoria ram</th>
						<td>{{laptop.ramMemory}}</td>
					</tr>
					<tr>
						<th scope="row">Frequencia de la memoria ram</th>
						<td>{{laptop.ramFrequency}}</td>
					</tr>
					<tr>
						<th scope="row">Tecnnología de la memoria ram</th>
						<td>{{laptop.ramTechology}}</td>
					</tr>
					<tr>
						<th scope="row">Disco duro</th>
						<td>{{laptop.hardDisk}}</td>
					</tr>
					<tr>
						<th scope="row">Fabricante de el procesador</th>
						<td>{{laptop.processorMaker}}</td>
					</tr>
					<tr>
						<th scope="row">Modelo de el procesador</th>
						<td>{{laptop.processorModel}}</td>
					</tr>
					<tr>
						<th scope="row">Velocidad de el procesador</th>
						<td>{{laptop.processorVelocity}}</td>
					</tr>
					<tr>
						<th scope="row">Núcleos de el procesador</th>
						<td>{{laptop.processorCore}}</td>
					</tr>
					<tr>
						<th scope="row">caché de el procesador</th>
						<td>{{laptop.processorCache}}</td>
					</tr>
					<tr>
						<th scope="row">Fabricante de la gráfica</th>
						<td>{{laptop.graphicMaker}}</td>
					</tr>
					<tr>
						<th scope="row">Modelo de la gráfica</th>
						<td>{{laptop.graphicModel}}</td>
					</tr>
					<tr>
						<th scope="row">Tecnología de la gráfica</th>
						<td>{{laptop.graphicTechnology}}</td>
					</tr>
					<tr>
						<th scope="row">Capacidad de la gráfica</th>
						<td>{{laptop.graphicCapacity}}</td>
					</tr>
					<tr>
						<th scope="row">Interfaz gráfica</th>
						<td>{{laptop.graphicInterface}}</td>
					</tr>
					<tr>
						<th scope="row">USB 2.0</th>
						<td>{{laptop.usb20}}</td>
					</tr>
					<tr>
						<th scope="row">USB 3.0</th>
						<td>{{laptop.usb30}}</td>
					</tr>
					<tr>
						<th scope="row">HDMI</th>
						<td>{{laptop.hdmi}}</td>
					</tr>
					<tr>
						<th scope="row">DVI</th>
						<td>{{laptop.dvi}}</td>
					</tr>
					<tr>
						<th scope="row">BLUETOOTH</th>
						<td>{{laptop.bluetooht}}</td>
					</tr>
					<tr>
						<th scope="row">S.O.</th>
						<td>{{laptop.os}}</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
{% endblock %}