src/Entity/Mouse.php
<?php

namespace App\Entity;

use App\Repository\MouseRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MouseRepository::class)
 */
class Mouse
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $dpi;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $type_2;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $connector;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $frequency;

    /**
     * @ORM\ManyToOne(targetEntity=SubCategory::class, inversedBy="mouse")
     * @ORM\JoinColumn(nullable=false)
     */
    private $idSubcategory;

    /**
     * @ORM\ManyToOne(targetEntity=Product::class, inversedBy="Mouse")
     * @ORM\JoinColumn(nullable=false)
     */
    private $idProduct;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDpi(): ?string
    {
        return $this->dpi;
    }

    public function setDpi(string $dpi): self
    {
        $this->dpi = $dpi;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getType2(): ?string
    {
        return $this->type_2;
    }

    public function setType2(string $type_2): self
    {
        $this->type_2 = $type_2;

        return $this;
    }

    public function getConnector(): ?string
    {
        return $this->connector;
    }

    public function setConnector(string $connector): self
    {
        $this->connector = $connector;

        return $this;
    }

    public function getFrequency(): ?string
    {
        return $this->frequency;
    }

    public function setFrequency(string $frequency): self
    {
        $this->frequency = $frequency;

        return $this;
    }

    public function getIdSubcategory(): ?SubCategory
    {
        return $this->idSubcategory;
    }

    public function setIdSubcategory(?SubCategory $idSubcategory): self
    {
        $this->idSubcategory = $idSubcategory;

        return $this;
    }

    public function getIdProduct(): ?Product
    {
        return $this->idProduct;
    }

    public function setIdProduct(?Product $idProduct): self
    {
        $this->idProduct = $idProduct;

        return $this;
    }
}

src/Entity/Screen.php
<?php

namespace App\Entity;

use App\Repository\ScreenRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ScreenRepository::class)
 */
class Screen
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $size;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $resolution;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $resolution_px;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $frequency;

    /**
     * @ORM\Column(type="string", length=5)
     */
    private $response_time;

    /**
     * @ORM\Column(type="string", length=8)
     */
    private $shine;

    /**
     * @ORM\Column(type="string", length=8, nullable=true)
     */
    private $view;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $connectors;

    /**
     * @ORM\ManyToOne(targetEntity=SubCategory::class, inversedBy="screens")
     * @ORM\JoinColumn(nullable=false)
     */
    private $idSubcategory;

    /**
     * @ORM\ManyToOne(targetEntity=Product::class, inversedBy="screens")
     * @ORM\JoinColumn(nullable=false)
     */
    private $idProduct;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSize(): ?string
    {
        return $this->size;
    }

    public function setSize(string $size): self
    {
        $this->size = $size;

        return $this;
    }

    public function getResolution(): ?string
    {
        return $this->resolution;
    }

    public function setResolution(string $resolution): self
    {
        $this->resolution = $resolution;

        return $this;
    }

    public function getResolutionPx(): ?string
    {
        return $this->resolution_px;
    }

    public function setResolutionPx(string $resolution_px): self
    {
        $this->resolution_px = $resolution_px;

        return $this;
    }

    public function getFrequency(): ?string
    {
        return $this->frequency;
    }

    public function setFrequency(string $frequency): self
    {
        $this->frequency = $frequency;

        return $this;
    }

    public function getResponseTime(): ?string
    {
        return $this->response_time;
    }

    public function setResponseTime(string $response_time): self
    {
        $this->response_time = $response_time;

        return $this;
    }

    public function getShine(): ?string
    {
        return $this->shine;
    }

    public function setShine(string $shine): self
    {
        $this->shine = $shine;

        return $this;
    }

    public function getView(): ?string
    {
        return $this->view;
    }

    public function setView(?string $view): self
    {
        $this->view = $view;

        return $this;
    }

    public function getConnectors(): ?string
    {
        return $this->connectors;
    }

    public function setConnectors(string $connectors): self
    {
        $this->connectors = $connectors;

        return $this;
    }

    public function getIdSubcategory(): ?SubCategory
    {
        return $this->idSubcategory;
    }

    public function setIdSubcategory(?SubCategory $idSubcategory): self
    {
        $this->idSubcategory = $idSubcategory;

        return $this;
    }

    public function getIdProduct(): ?Product
    {
        return $this->idProduct;
    }

    public function setIdProduct(?Product $idProduct): self
    {
        $this->idProduct = $idProduct;

        return $this;
    }
}

src/Controller/SubCategoryController.php
<?php

namespace App\Controller;

use App\Entity\Category;
use App\Entity\SubCategory;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class SubCategoryController extends AbstractController
{
    /**
     * @Route("/sub/category", name="sub_category")
     */
    public function index(): Response
    {
        return $this->render('sub_category/index.html.twig', [
            'controller_name' => 'SubCategoryController',
        ]);
    }

    /**
     * @Route("/subCategory/get", name="app_get_subcategories", methods={"POST","GET"}, options={"expose"=true})
     */
    public function getSubcategories(Request $request)
    {
        if($request->isXmlHttpRequest()){
            $content=json_decode($request->getContent());
            $array_subcat = [];
            $entityManager = $this->getDoctrine()->getManager();
            $category = $entityManager->getRepository(Category::class)->findOneBy(['name' => $content]);
            $subcategories = $category->getSubcategories();
            foreach($subcategories as $s){
                array_push($array_subcat, $s->getName());
            }
            return new Response(json_encode($array_subcat));
        }
    }

    /**
     * @Route("/subCategory/features", name="app_get_features", methods={"POST","GET"}, options={"expose"=true})
     */
    public function getFeatures(Request $request)
    {
        if($request->isXmlHttpRequest()){
            $content=json_decode($request->getContent());
            $entityManager = $this->getDoctrine()->getManager();
            $subcategory = $entityManager->getRepository(SubCategory::class)->findOneBy(['name' => $content]);
            return new Response(json_encode($subcategory->getCaracteristics()));
        }
    }
}

templates/subcategory/auriculares.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ProductController!
{% endblock %}

{% block body %}
<h2 class="h2 col-12 text-center mt-3">Auriculares</h2>
		<div class="container-fluid col-12 mt-3 row justify-lg-content-around justify-xs-content-center ">
			{% for j, product in productHeadphones %}
					<div class="col-12 col-lg-3 offset-lg-1 card p-3 mt-5 mb-5" style="width: 18rem;">
						<img class="card-img-top" src="{{ asset('images/Earphones/' ~ product.picture ) }}" alt="Card image cap" width"250px" height="250px"/>
						<div class="card-body">
							<h5 class="card-title">{{ product.name }}</h5>
							<p class="card-text">
								Dispositivo: {{ headphones[j].type}}</p>
							<p class="card-text">
								Conexión: {{ headphones[j].connection}}</p>
							<p class="card-text">Stock: 
								{{ product.stock}}</p>
							<p class="card-text">Precio: 
								{{ product.price}}
								$</p>
							<a href=" {{ asset('/product/getProduct/Auriculares/' ~ product.id ) }} " class="col-12 btn btn-primary btn-card">Ver producto</a>
						</div>
					</div>
			{% endfor %}
		</div>
{% endblock %}

templates/subcategory/cargador.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ProductController!
{% endblock %}

{% block body %}
<h2 class="h2 col-12 text-center mt-3">Cargadores</h2>
		<div class="container-fluid col-12 mt-3 row justify-lg-content-around justify-xs-content-center">
			{% for j, product in produckCharger %}
					<div class="col-12 col-lg-3 offset-lg-1 card p-3 mt-5 mb-5" style="width: 18rem;">
						<img class="card-img-top" src="{{ asset('images/Chargers/' ~ product.picture ) }}" alt="Card image cap" width"250px" height="250px"/>
						<div class="card-body">
							<h5 class="card-title">{{ product.name }}</h5>
							<p class="card-text">
								Conexión: {{ charger[j].connection}}</p>
							<p class="card-text">
								Amperaje: {{ charger[j].amperage}}</p>
							<p class="card-text">Stock: 
								{{ product.stock}}</p>
							<p class="card-text">Precio: 
								{{ product.price}}
								$</p>
							<a href=" {{ asset('/product/getProduct/Cargador/' ~ product.id ) }} " class="btn btn-primary btn-card col-12">Ver producto</a>
						</div>
					</div>
			{% endfor %}
		</div>
{% endblock %}

templates/subcategory/funda.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ProductController!
{% endblock %}

{% block body %}
<h2 class="h2 col-12 text-center mt-3">Fundas</h2>
		<div class="container-fluid col-12 mt-3 row justify-lg-content-around justify-xs-content-center">
			{% for j, product in productCases %}
					<div class="col-12 col-lg-3 offset-lg-1 card p-3 mt-5 mb-5" style="width: 18rem;">
						<img class="card-img-top" src="{{ asset('images/DeviceCases/' ~ product.picture ) }}" alt="Card image cap" width"250px" height="250px"/>
						<div class="card-body">
							<h5 class="card-title">{{ product.name }}</h5>
							<p class="card-text">
								Dispositivo: {{ cases[j].device}}</p>
							<p class="card-text">
								Color: {{ cases[j].color}}</p>
							<p class="card-text">Stock: 
								{{ product.stock}}</p>
							<p class="card-text">Precio: 
								{{ product.price}}
								$</p>
							<a href=" {{ asset('/product/getProduct/Funda/' ~ product.id ) }} " class="btn btn-primary btn-card col-12">Ver producto</a>
						</div>
					</div>
			{% endfor %}
		</div>
{% endblock %}

templates/subcategory/pantalla.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ProductController!
{% endblock %}

{% block body %}
<h2 class="h2 col-12 text-center mt-3">Pantallas</h2>
		<div class="container-fluid col-12 mt-3 row justify-lg-content-center justify-xs-content-center">
			{% for j, product in productScreens %}
					<div class="col-12 col-lg-3 offset-lg-1 card p-3 mt-5 mb-5" style="width: 18rem;">
						<img class="card-img-top" src="{{ asset('images/Screens/' ~ product.picture ) }}" alt="Card image cap" width"250px" height="250px"/>
						<div class="card-body">
							<h5 class="card-title">{{ product.name }}</h5>
							<p class="card-text">
								Tamaño: {{ screens[j].size}}</p>
							<p class="card-text">
								Resolucion : {{ screens[j].resolution}} 
								- {{ screens[j].resolutionPx}}</p>
							<p class="card-text">
								Conector: 
								{{ screens[j].connectors}}</p>
							<p class="card-text">Stock: 
								{{ product.stock}}</p>
							<p class="card-text">Precio: 
								{{ product.price}}
								$</p>
							<a href=" {{ asset('/product/getProduct/Pantalla/' ~ product.id ) }} " class="col-12 btn btn-primary btn-card">Ver producto</a>
						</div>
					</div>
			{% endfor %}
		</div>
{% endblock %}

templates/subcategory/pcSobremesa.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ProductController!
{% endblock %}

{% block body %}
<h2 class="h2 col-12 text-center mt-3">PC/Sobremesa</h2>
		<div class="container-fluid col-12 mt-3 row justify-lg-content-around justify-xs-content-center ">
			{% for j, product in productsDesktops %}
					<div class="col-12 col-lg-3 offset-lg-1 card p-3 mt-5 mb-5" style="width: 18rem;">
						<img class="card-img-top" src="{{ asset('images/Desktops/' ~ product.picture ) }}" alt="Card image cap" width"250px" height="250px"/>
						<div class="card-body">
							<h5 class="card-title">{{ product.name }}</h5>
							<p class="card-text">
								Memoria Ram:{{ desktops[j].ramMemory}}</p>
							<p class="card-text">
								Procesador :<br>{{ desktops[j].processorModel}}</p>
							<p class="card-text">
								O.S:
								{{ desktops[j].os}}</p>
							<p class="card-text">Stock:
								{{ product.stock}}</p>
							<p class="card-text">Precio:
								{{ product.price}}
								$</p>
							<a href=" {{ asset('/product/getProduct/PCSobremesa/' ~ product.id ) }} " class="col-12 btn btn-primary btn-card">Ver producto</a>
						</div>
					</div>
			{% endfor %}
		</div>
{% endblock %}

templates/subcategory/portatil.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ProductController!
{% endblock %}

{% block body %}
<h2 class="h2 col-12 text-center mt-3">Portátiles</h2>
		<div class="container-fluid col-12 mt-3 row justify-lg-content-around justify-xs-content-center">
			{% for j, product in productsLaptops %}
					<div class="col-12 col-lg-3 offset-lg-1 card p-3 mt-5 mb-5" style="width: 18rem;">
						<img class="card-img-top" src="{{ asset('images/Laptops/' ~ product.picture ) }}" alt="Card image cap" width"250px" height="250px"/>
						<div class="card-body">
							<h5 class="card-title">{{ product.name }}</h5>
							<p class="card-text">
								Memoria Ram:{{ laptops[j].ramMemory}}</p>
							<p class="card-text">
								Procesador :<br>{{ laptops[j].processorModel}}</p>
							<p class="card-text">
								O.S:
								{{ laptops[j].os}}</p>
							<p class="card-text">Stock:
								{{ product.stock}}</p>
							<p class="card-text">Precio:
								{{ product.price}}
								$</p>
							<a href=" {{ asset('/product/getProduct/Portatil/' ~ product.id ) }} " class="btn btn-primary btn-card col-12">Ver producto</a>
						</div>
					</div>
			{% endfor %}
		</div>
{% endblock %}

templates/subcategory/raton.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ProductController!
{% endblock %}

{% block body %}
<h2 class="h2 col-12 text-center mt-3">Ratones</h2>
		<div class="container-fluid col-12 mt-3 row justify-lg-content-center justify-xs-content-center">
			{% for j, product in productMouses %}
					<div class="col-12 col-lg-3 offset-lg-1 card p-3 mt-5 mb-5" style="width: 18rem;">
						<img class="card-img-top" src="{{ asset('images/Mouses/' ~ product.picture ) }}" alt="Card image cap" width"250px" height="250px"/>
						<div class="card-body">
							<h5 class="card-title">{{ product.name }}</h5>
							<p class="card-text">
								Tipo de raton:{{ mouses[j].type}}</p>
							<p class="card-text">
								Tipo de uso :<br>{{ mouses[j].type2}}</p>
							<p class="card-text">
								Conexión:
								{{ mouses[j].connector}}</p>
							<p class="card-text">Stock:
								{{ product.stock}}</p>
							<p class="card-text">Precio:
								{{ product.price}}
								$</p>
							<a href=" {{ asset('/product/getProduct/Raton/' ~ product.id ) }} " class="col-12 btn btn-primary btn-card">Ver producto</a>
						</div>
					</div>
			{% endfor %}
		</div>
{% endblock %}

templates/subcategory/smartwatch.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ProductController!
{% endblock %}

{% block body %}
<h2 class="h2 col-12 text-center mt-3">smartWatchs</h2>
		<div class="container-fluid col-10 mt-3 row justify-content-around">
			{% for j, product in productsmartwatch %}
					<div class="col-12 col-lg-3 offset-lg-1 card p-3 mt-5 mb-5" style="width: 18rem;">
						<img class="card-img-top" src="{{ asset('images/Smartwatchs/' ~ product.picture ) }}" alt="Card image cap" width"250px" height="250px"/>
						<div class="card-body">
							<h5 class="card-title">{{ product.name }}</h5>
							<p class="card-text">
								S.O. :{{ smartwatch[j].so}}</p>
							<p class="card-text">
								Calidad de imagen:<br>{{ smartwatch[j].resolution}}</p>
							<p class="card-text">
								Resolución:
								{{ smartwatch[j].resolutionPx}}</p>
							<p class="card-text">Stock:
								{{ product.stock}}</p>
							<p class="card-text">Precio:
								{{ product.price}}
								$</p>
							<a href=" {{ asset('/product/getProduct/Smartwatch/' ~ product.id ) }} " class="btn btn-primary btn-card col-12">Ver producto</a>
						</div>
					</div>
			{% endfor %}
		</div>
{% endblock %}

templates/subcategory/teclado.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ProductController!
{% endblock %}

{% block body %}
<h2 class="h2 col-12 text-center mt-3">Teclados</h2>
		<div class="container-fluid col-12 mt-3 row justify-lg-content-center justify-xs-content-center">
			{% for j, product in productsKeyboards %}
					<div class=" col-12 col-lg-3 offset-lg-1 card p-3 mt-5 mb-5" style="width: 18rem;">
						<img class="card-img-top" src="{{ asset('images/Keyboards/' ~ product.picture ) }}" alt="Card image cap" width"250px" height="250px"/>
						<div class="card-body">
							<h5 class="card-title">{{ product.name }}</h5>
							<p class="card-text">
								Tipo de escritura: {{ keyboards[j].type}}</p>
							<p class="card-text">
								Tipo de uso : {{ keyboards[j].type2}}</p>
							<p class="card-text">
								Conexión: 
								{{ keyboards[j].connector}}</p>
							<p class="card-text">Stock: 
								{{ product.stock}}</p>
							<p class="card-text">Precio: 
								{{ product.price}}
								$</p>
							<a href=" {{ asset('/product/getProduct/Teclado/' ~ product.id ) }} " class="col-12 btn btn-primary btn-card">Ver producto</a>
						</div>
					</div>
			{% endfor %}
		</div>
{% endblock %}

templates/subcategory/webcam.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ProductController!
{% endblock %}

{% block body %}
<h2 class="h2 col-12 text-center mt-3">Webcams</h2>
		<div class="container-fluid col-12 mt-3 row justify-lg-content-around justify-xs-content-center">
			{% for j, product in productWebcam %}
					<div class="col-12 col-lg-3 offset-lg-1 card p-3 mt-5 mb-5" style="width: 18rem;">
						<img class="card-img-top" src="{{ asset('images/Webcams/' ~ product.picture ) }}" alt="Card image cap" width"250px" height="250px"/>
						<div class="card-body">
							<h5 class="card-title">{{ product.name }}</h5>
							<p class="card-text">
								Resolución:{{ webcams[j].resolutionPx}}</p>
							<p class="card-text">
								Sonido: {{ webcams[j].sound}}</p>
							<p class="card-text">
								Conexión:
								{{ webcams[j].connection}}</p>
							<p class="card-text">Stock:
								{{ product.stock}}</p>
							<p class="card-text">Precio:
								{{ product.price}}
								$</p>
							<a href=" {{ asset('/product/getProduct/Webcam/' ~ product.id ) }} " class="btn btn-primary btn-card col-12">Ver producto</a>
						</div>
					</div>
			{% endfor %}
		</div>
{% endblock %}