src/Entity/Screen.php
<?php

namespace App\Entity;

use App\Repository\ScreenRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ScreenRepository::class)
 */
class Screen
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $size;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $resolution;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $resolution_px;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $frequency;

    /**
     * @ORM\Column(type="string", length=5)
     */
    private $response_time;

    /**
     * @ORM\Column(type="string", length=8)
     */
    private $shine;

    /**
     * @ORM\Column(type="string", length=8, nullable=true)
     */
    private $view;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $connectors;

    /**
     * @ORM\ManyToOne(targetEntity=SubCategory::class, inversedBy="screens")
     * @ORM\JoinColumn(nullable=false)
     */
    private $idSubcategory;

    /**
     * @ORM\ManyToOne(targetEntity=Product::class, inversedBy="screens")
     * @ORM\JoinColumn(nullable=false)
     */
    private $idProduct;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSize(): ?string
    {
        return $this->size;
    }

    public function setSize(string $size): self
    {
        $this->size = $size;

        return $this;
    }

    public function getResolution(): ?string
    {
        return $this->resolution;
    }

    public function setResolution(string $resolution): self
    {
        $this->resolution = $resolution;

        return $this;
    }

    public function getResolutionPx(): ?string
    {
        return $this->resolution_px;
    }

    public function setResolutionPx(string $resolution_px): self
    {
        $this->resolution_px = $resolution_px;

        return $this;
    }

    public function getFrequency(): ?string
    {
        return $this->frequency;
    }

    public function setFrequency(string $frequency): self
    {
        $this->frequency = $frequency;

        return $this;
    }

    public function getResponseTime(): ?string
    {
        return $this->response_time;
    }

    public function setResponseTime(string $response_time): self
    {
        $this->response_time = $response_time;

        return $this;
    }

    public function getShine(): ?string
    {
        return $this->shine;
    }

    public function setShine(string $shine): self
    {
        $this->shine = $shine;

        return $this;
    }

    public function getView(): ?string
    {
        return $this->view;
    }

    public function setView(?string $view): self
    {
        $this->view = $view;

        return $this;
    }

    public function getConnectors(): ?string
    {
        return $this->connectors;
    }

    public function setConnectors(string $connectors): self
    {
        $this->connectors = $connectors;

        return $this;
    }

    public function getIdSubcategory(): ?SubCategory
    {
        return $this->idSubcategory;
    }

    public function setIdSubcategory(?SubCategory $idSubcategory): self
    {
        $this->idSubcategory = $idSubcategory;

        return $this;
    }

    public function getIdProduct(): ?Product
    {
        return $this->idProduct;
    }

    public function setIdProduct(?Product $idProduct): self
    {
        $this->idProduct = $idProduct;

        return $this;
    }
}

src/Controller/ScreenController.php
<?php

namespace App\Controller;

use App\Repository\SubCategoryRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ScreenController extends AbstractController
{
    /**
     * @Route("/listSubCategories/Pantalla", name="app_listSubCategoriesPantalla")
     */
    public function listSubCategoriesTeclado (SubCategoryRepository $SubCategoryRepository): Response{
        $SubCategory = $SubCategoryRepository->findOneBy(['name' => 'Pantalla']);
        $productScreens = [];
        $screens = null;
       
        $screens = $SubCategory->getScreens();
        foreach ($screens as $d) {
            array_push($productScreens, $d->getIdProduct());
        }

        return $this->render('subcategory/pantalla.html.twig', [
            'productScreens' => $productScreens,
            'screens' => $screens
        ]);
    }
}

templates/screen/screen.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello laptopController!
{% endblock %}

{% block body %}
	<div class="col-12 row justify-content-xs-center justify-content-lg-around mt-5">
		<div class="col-xs-11 col-lg-4 offset-xs-1 offset-lg-1 row justify-content-center">
			<img class="" src="{{ asset('images/Screens/' ~ product.picture ) }}" alt="Card image cap" width"500px" height="500px"/>
		</div>

		<div class="col-xs-11 col-lg-6 row justify-content-xs-center justify-content-lg-start">
			<h1 class="h2 col-xs-3 offset-xs-1 col-lg-11 mt-4 text-center text-lg-left">
				{{product.name}}
			</h1>
			<h4 class="h4 col-xs-3 col-lg-11 mt-4 lead">
				Fabricante:
				{{product.mark}}
			</h4>
			<h4 class="h4 col-xs-3 col-lg-11 mt-4 lead">
				Modelo:
				{{product.model}}
			</h4>
			<h4 class="h4 col-xs-3 col-lg-11 mt-4 lead">
				Calidad de imagen:
				{{screen.resolution}}
			</h4>
			<h4 class="h4 col-xs-3 col-lg-11 mt-4 lead">
				Resolución:
				{{screen.resolutionPx}}</h4>
			<h4 class="h4 col-xs-3 col-lg-11 mt-4 lead">
				Conector:
				{{ screen.connectors}}</h4>
			<h4 class="h4 col-xs-3 col-lg-11 mt-4 lead">
				Precio:
				{{product.price}}
				$</h4>
			<select id="stockSelect"class="col-xs-12  col-lg-6 mt-4 lead form-select" aria-label="Default select example">
				<option selected>1</option>
                {% for i in 2..product.stock %}
                    <option value="1">{{ i }}</option>
                {% endfor %}
			</select>
			<div class="w-100"></div>
			<button href="" onClick="checkAddCart({{product.id}})"  class=" col-xs-12 col-lg-6 mt-4 lead btn btn-primary">
				Añadir al carrito
			</button>
		</div>
		<div class="col-xs-11 col-lg-6 mt-3 row">
			<h2 class="h2 col-12">
				Descripción</h2>
			<p class="p col-12 leaf text-align-justify">
				{{product.description}}
			</p>
			<table class="mt-4 col-12 table">
				<tbody>
					<tr>
						<th scope="row">Fabricante</th>
						<td>{{product.maker}}</td>
					</tr>
					<tr>
						<th scope="row">Nombre</th>
						<td>{{product.name}}</td>
					</tr>
					<tr>
						<th scope="row">Modelo</th>
						<td>{{product.model}}</td>
					</tr>
					<tr>
						<th scope="row">Dimensiones</th>
						<td>{{product.dimensions}}</td>
					</tr>
					<tr>
						<th scope="row">Peso</th>
						<td>{{product.weight}}</td>
					</tr>
					<tr>
						<th scope="row">Año</th>
						<td>{{product.year}}</td>
						<tr>
					<th scope="row">Calidad de imagen:</th>
						<td>{{screen.resolution}}</td>
					</tr>
					</tr>
					<tr>
						<th scope="row">Resolución:</th>
						<td>{{screen.resolutionPx}}</td>
					</tr>
					<tr>
						<th scope="row">Frequencia:</th>
						<td>{{screen.frequency}}</td>
					</tr>
					<tr>
						<th scope="row">Tiempo de respuesta:</th>
						<td>{{screen.responseTime}}</td>
					</tr>
					<tr>
						<th scope="row">Brillo:</th>
						<td>{{screen.shine}}</td>
					</tr>
					<tr>
						<th scope="row">Disposisción de pantalla:</th>
						<td>{{screen.view}}</td>
					</tr>
					<tr>
						<th scope="row">Conectores:</th>
						<td>{{screen.connectors}}</td>
					</tr>
					
				</tbody>
			</table>
		</div>
	</div>
{% endblock %}